### ISSUE TITLE
Upgrade issues

### ISSUE THREAD

**Issue by sphkress** [simonschaufi/macina_banners#1]
I had the previous version installed and working in a 6.2 environment. After step by step upgrading, in T37.6, the banners (v. 1.5.6) are not shown anymore. 
I have emptied typo3temp and all other caches. The documentation is also not updated.

**Comment by simonschaufi** [comment]
The only thing I fixed was an issue with the Orientation but the rest is still the same code. Please do some debugging yourself.

**Comment by sphkress** [comment]
I got it working by commenting out line 177 in Plugin/Pi1.php .
Debugging is quite hard because I purely can guess what's going on...  

For further investigation:
I am using the TypoScript variant to include the banner directly in the page. The placement is irrelevant for me, so i have chosen to set plugin.tx_macinabanners_pi1.placement = all (which was working in the previous versions). Apparently it's not anymore and if the positioning is left empty, no banners are shown at all. 
Workaround: 

set plugin.tx_macinabanners_pi1.placement = top,bottom,left,right 
and select at least one position per banner.

However, it would be great to have a possibility to disable to placements in general when they are not needed at all (making things easier for editors).

**Comment by simonschaufi** [comment]
It should work, if you leave the placement empty (instead of `all`) because of https://github.com/simonschaufi/macina_banners/blob/master/Classes/Plugin/Pi1.php#L160. Could you please verify?

**Comment by sphkress** [comment]
Ok, i can confirm, this is working.

After hours of debugging i finally seem to understand this a bit better. However, it's not documented and therefore for regular users very difficult to track down.

Maybe you could add some information, e.g. in ext_typoscript_setup.txt:

	# show banners with this attribute, default options are: "top, left, bottom, right", all Descriptions of Banner Categories can be used. Leave empty to ignore the placement at all.
	placement = top
