### ISSUE TITLE
Add condition for EXT:lang language file

### ISSUE THREAD

**Issue by lochmueller** [simonschaufi/macina_banners#2]
For TYPO3 7.x it should be "LLL:EXT:lang/locallang_general.xlf" (without path to Resources/Private/Language/).

Regards,
Tim

**Comment by simonschaufi** [comment]
Could you patch that yourself and make a PR? that would be nice!

**Comment by lochmueller** [comment]
Hey Simon,
I am working on several fixes at the moment (also use News as Banner).
I will send you the PR after I am done.
Regards,
Tim

**Comment by simonschaufi** [comment]
@lochmueller still waiting for the PR ;)

**Comment by lochmueller** [comment]
Hey @simonschaufi ... sorry for my late response. We switched from macina_banners to a standalone solution. So there was so futher invests into EXT:macina_banners
